"""
Django settings for fake_review_detector project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default):
    """Read a boolean from the environment ('1', 'true', 'yes' -> True)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
# On Vercel this comes from the SECRET_KEY environment variable.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-k1=i+#&x@u2y&p$sx_bvfl!ht+ker#1f-#6oo3s&9@hy$s^)9j',
)

# Vercel sets VERCEL=1 in its runtime environment.
ON_VERCEL = bool(os.environ.get('VERCEL'))

# SECURITY WARNING: don't run with debug turned on in production!
# True locally, False on Vercel automatically — so a forgotten environment
# variable can't leave the deployed site running in debug mode.
DEBUG = _env_bool('DEBUG', not ON_VERCEL)

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Always trust Vercel's own domain and the local host names. Without this, a
# missing ALLOWED_HOSTS variable makes Django reject every request with a bare
# 400 DisallowedHost, which is hard to read as a configuration problem.
for _host in ('.vercel.app', 'localhost', '127.0.0.1', '[::1]'):
    if _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

# Vercel serves over HTTPS, so POST forms need the origin trusted.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.vercel.app').split(',')
    if o.strip()
]

if not DEBUG:
    # Vercel terminates TLS at its proxy and forwards this header; without it
    # Django thinks the request is plain HTTP and secure cookies never stick.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves the collected static files (admin CSS etc.) in production.
    # Added only when the package is installed, so local dev never breaks.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

try:
    import whitenoise  # noqa: F401
except ImportError:
    pass
else:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'fake_review_detector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fake_review_detector.wsgi.application'


# Database
# Local: SQLite, exactly as before.
# Production: set DATABASE_URL to the Supabase connection string and this switches
# to Postgres automatically. Use Supabase's *Transaction pooler* URL (port 6543) —
# a serverless function opens a new connection per request and the direct
# connection (5432) runs out of slots quickly.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.environ.get('DATABASE_URL')

# On Vercel the SQLite fallback above can never work: db.sqlite3 is gitignored
# and is not in vercel.json's includeFiles, so it isn't in the bundle at all. A
# missing DATABASE_URL would surface as a confusing "unable to open database
# file" deep inside a request, so say plainly what is wrong at import time.
# Deliberately NOT a hard crash: raising here would take down the pages that
# work fine without a database (the homepage), turning a partial outage into a
# total one. /healthz/ reports it instead.
MISSING_DATABASE_URL = bool(ON_VERCEL and not DATABASE_URL)

if DATABASE_URL:
    import dj_database_url

    _db = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,          # never reuse across invocations on serverless
        ssl_require=True,
    )
    _options = _db.setdefault('OPTIONS', {})

    # Fail fast instead of hanging. Without this, an unreachable database makes
    # psycopg block until Vercel's gateway gives up and returns a bare 504 with
    # nothing in the function log. Five seconds turns that into a real
    # OperationalError you can actually read.
    _options.setdefault('connect_timeout', 5)

    # Supabase's pooler URL ends with ?pgbouncer=true. That is a Prisma flag —
    # psycopg treats it as an unknown connection option and refuses to connect.
    _options.pop('pgbouncer', None)

    try:
        import psycopg  # noqa: F401  (psycopg 3)
    except ImportError:
        pass
    else:
        # PgBouncer in transaction mode hands out a different backend connection
        # per statement, so server-side prepared statements can't be reused.
        _options['prepare_threshold'] = None

    DATABASES['default'] = _db
    # ...same reason: a server-side cursor can't outlive the transaction.
    DISABLE_SERVER_SIDE_CURSORS = True


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = 'static/'

# collectstatic writes here; the folder is committed so Vercel can serve it
# through WhiteNoise without needing a build step.
STATIC_ROOT = BASE_DIR / 'staticfiles'

if (BASE_DIR / 'static').is_dir():
    STATICFILES_DIRS = [BASE_DIR / 'static']

# Product images.
#
# MEDIA_URL stays '/', so the paths stored in the database keep resolving to
# /Product_Images/<file>. The files sit in media/ rather than the project root
# because WHITENOISE_ROOT publishes everything under it at the site root —
# pointing that at BASE_DIR would serve settings.py and the database too.
#
#   Local  -> the static() helper in reviews/urls.py serves them while DEBUG is on.
#   Vercel -> WhiteNoise serves them straight out of the deployed bundle.
#
# The folder must NOT be named "public": Vercel treats public/ as a framework's
# static output directory and keeps it out of the serverless function bundle,
# so WhiteNoise found nothing there and every image 404'd on the live site.
MEDIA_ROOT = BASE_DIR / 'media'

WHITENOISE_ROOT = MEDIA_ROOT

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if not DEBUG:
    try:
        import whitenoise.storage  # noqa: F401
    except ImportError:
        pass
    else:
        # Compressed but NOT manifest-based: a missing manifest would 500 the
        # whole site if collectstatic was ever skipped.
        STORAGES['staticfiles'] = {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        }


# =========================
# ✅ FIX ADDED (IMPORTANT)
# =========================
LOGIN_URL = '/login/'